blank_issues_enabled: false
contact_links:
  - name: WB Community Support
    url: https://github.com/gld/worldbank
    about: Please ask and answer questions here.
  - name: WB Security Bug Bounty
    url: https://github.com/gld/worldbank
    about: Please report security vulnerabilities here.
