name: Traditional  Bug Report
description: File a bug report without images
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex.email@example.com
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: Country
    attributes:
      label: Country
      description: What country is this issue related to? Please indicate the name and the ISO code (e.g. COL)
       placeholder: Tell us the country name here.
      value: "e.g. MEX "
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: What version are you seeing the problem on?
      multiple: true
      options:
        - V01
        - V02
        - V03
        - V04
        - Multiple or other (please explain in the log)
  - type: textarea
    id: year
    attributes:
      label: What year are you seeing the problem on?
      description: Please, specify the year(s) where the problem is present.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/worldbank/gld/blob/c3e0e28037247a64d7348824c9fdf03d142ad1d7/Support/E%20-%20Community%20Guidelines/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
